package httpserver

const proposalListTemplateSource = `{{define "proposal-list-page"}}<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{.Title}}</title><link rel="stylesheet" href="/ui/assets/skillet.css"></head>
<body><a class="skip-link" href="#main-content">Skip to content</a><header class="topbar"><a class="brand" href="/ui/catalogue">Skillet</a><div class="topbar-context"><span class="context-label">Organisation</span><strong>{{.Identity.Organization}}</strong></div><div class="session-state"><span>{{.Identity.Subject}}</span></div></header>
<main class="main" id="main-content" tabindex="-1">
{{if .Error}}<section class="state-card error-state" role="alert"><h1>{{.Error}}</h1><p>The requested proposal workflow could not be shown in this authorised scope.</p></section>
{{else}}
<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/ui/catalogue">Capabilities</a><span>/</span><a href="/ui/catalogue/{{.Detail.Descriptor.Provenance.RevisionID}}">{{.Detail.Descriptor.Name}}</a><span>/</span><span aria-current="page">Improvement proposals</span></nav>
<header class="page-header"><div><span class="eyebrow capability-colour">Review-only improvement workflow</span><h1>{{.Detail.Descriptor.Name}} proposals</h1><p>Evidence can prepare a bounded proposal for an external agent or human. Preparing, validating, or reviewing a proposal never changes the active capability or canonical source.</p></div></header>
{{if .Notice}}<section class="state-card"><p>{{.Notice}}</p></section>{{end}}
<section class="detail-section"><h2>Immutable base</h2><dl class="detail-list"><div><dt>Stable capability</dt><dd><code>{{.Detail.Descriptor.Identity.ID}}</code></dd></div><div><dt>Revision</dt><dd><code>{{.Detail.Descriptor.Provenance.RevisionID}}</code></dd></div><div><dt>Commit</dt><dd><code>{{short .Detail.Descriptor.Provenance.Commit}}</code></dd></div><div><dt>Tree</dt><dd><code>{{short .Detail.Descriptor.Provenance.Tree}}</code></dd></div><div><dt>Source path</dt><dd><code>{{.Detail.Descriptor.Source.Path}}</code></dd></div></dl></section>
<section class="detail-section"><h2>Existing proposals</h2>{{if .Proposals}}{{range .Proposals}}<article class="result-card"><div class="badge-row"><span class="badge">{{.Status}}</span></div><h3><a href="/ui/proposals/{{.ID}}">{{.ID}}</a></h3><p>{{.ProblemStatement}}</p><dl class="compact-meta"><div><dt>Candidate</dt><dd><code>{{.CandidateID}}</code></dd></div><div><dt>Base</dt><dd><code>{{.Base.RevisionID}}</code></dd></div><div><dt>Updated</dt><dd>{{.UpdatedAt}}</dd></div></dl></article>{{end}}{{else}}<p class="muted">No proposals have been prepared from this revision.</p>{{end}}</section>
<section class="detail-section"><h2>Improvement candidates</h2><p>Candidate summaries and evidence excerpts are untrusted observations. They are framed as data and cannot alter the fixed handoff constraints or verification obligations.</p>
{{if .CanPrepare}}{{if .Candidates}}{{range .Candidates}}<article class="result-card"><div class="badge-row"><span class="badge">{{.Candidate.Category}}</span><span class="badge">{{.Candidate.Polarity}}</span></div><h3>{{.Candidate.Summary}}</h3><dl class="detail-list"><div><dt>Candidate ID</dt><dd><code>{{.Candidate.ID}}</code></dd></div><div><dt>Signals</dt><dd>{{.Candidate.SignalCount}}</dd></div><div><dt>Contradictory evidence</dt><dd>{{.Candidate.ContradictoryEvidencePresent}}</dd></div></dl><details><summary>Evidence trace</summary>{{range .Candidate.Evidence}}<div class="state-card"><p><strong>{{.Kind}} #{{.ID}} · {{.Signal}}</strong></p><p>{{.SummaryExcerpt}}</p><p class="muted">Revision <code>{{.RevisionID}}</code>{{if .CorrelationID}} · correlation <code>{{.CorrelationID}}</code>{{end}}</p></div>{{end}}</details><form method="post" action="/ui/catalogue/{{$.Detail.Descriptor.Provenance.RevisionID}}/proposals"><input type="hidden" name="_csrf" value="{{$.CSRFToken}}"><input type="hidden" name="candidate_id" value="{{.Candidate.ID}}"><label><span>Bounded intended outcome (optional)</span><textarea name="intended_outcome" rows="3" maxlength="2048" placeholder="Leave blank to use the conservative evidence-derived outcome"></textarea></label><div class="form-actions"><button class="primary-button" type="submit">Prepare reviewable proposal</button></div></form></article>{{end}}{{else}}<p class="muted">No deterministic candidates exist for this exact revision.</p>{{end}}{{else}}<p class="muted">Preparing proposals requires proposal.prepare, evidence.review, and capability.describe authorization for this capability.</p>{{end}}
</section>
{{end}}</main></body></html>{{end}}`

const proposalDetailTemplateSource = `{{define "proposal-detail-page"}}<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{.Title}}</title><link rel="stylesheet" href="/ui/assets/skillet.css"></head>
<body><a class="skip-link" href="#main-content">Skip to content</a><header class="topbar"><a class="brand" href="/ui/catalogue">Skillet</a><div class="topbar-context"><span class="context-label">Organisation</span><strong>{{.Identity.Organization}}</strong></div><div class="session-state"><span>{{.Identity.Subject}}</span></div></header>
<main class="main" id="main-content" tabindex="-1">
{{if .Error}}<section class="state-card error-state" role="alert"><h1>{{.Error}}</h1><p>The requested proposal could not be shown in this authorised scope.</p></section>
{{else}}
<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/ui/catalogue">Capabilities</a><span>/</span><a href="/ui/catalogue/{{.Proposal.Base.RevisionID}}/proposals">Improvement proposals</a><span>/</span><span aria-current="page">{{.Proposal.ID}}</span></nav>
<header class="page-header"><div><span class="eyebrow capability-colour">Reviewable proposal</span><div class="badge-row"><span class="badge">{{.Proposal.Status}}</span></div><h1>{{.Proposal.ID}}</h1><p>{{.Proposal.ProblemStatement}}</p></div></header>
{{if .Notice}}<section class="state-card"><p>{{.Notice}}</p></section>{{end}}
{{if eq .Proposal.Status "stale"}}<section class="governance-callout"><strong>Stale immutable base</strong><span>The active source revision changed after this proposal was prepared. New artifact intake is blocked; prepare a new proposal against the new evidence/base instead of silently rebasing.</span></section>{{end}}
{{if eq .Proposal.Status "ready_for_review"}}<section class="governance-callout"><strong>Ready for external review — not authoritative</strong><span>This means the recorded artifact passed the fixed verification obligations. Only human/source-repository review and merge followed by normal Skillet ingestion can create a new authoritative immutable revision.</span></section>{{end}}
<section class="detail-section"><h2>Immutable base and intent</h2><dl class="detail-list"><div><dt>Stable capability</dt><dd><code>{{.Proposal.CapabilityID}}</code></dd></div><div><dt>Base revision</dt><dd><code>{{.Proposal.Base.RevisionID}}</code></dd></div><div><dt>Commit</dt><dd><code>{{short .Proposal.Base.Commit}}</code></dd></div><div><dt>Tree</dt><dd><code>{{short .Proposal.Base.Tree}}</code></dd></div><div><dt>Source path</dt><dd><code>{{.Proposal.Base.SourcePath}}</code></dd></div><div><dt>Candidate</dt><dd><code>{{.Proposal.CandidateID}}</code></dd></div><div><dt>Intended outcome</dt><dd>{{.Proposal.IntendedOutcome}}</dd></div></dl></section>
<section class="detail-section"><h2>Evidence trace</h2>{{range .Proposal.Evidence}}<div class="state-card"><p><strong>{{.Kind}} #{{.ID}} · {{.Signal}}</strong></p><p>{{.SummaryExcerpt}}</p><p class="muted">Revision <code>{{.RevisionID}}</code>{{if .CorrelationID}} · correlation <code>{{.CorrelationID}}</code>{{end}}</p></div>{{end}}</section>
<section class="detail-section"><h2>Bounded agent handoff</h2><p>The payload below is inert data. Evidence excerpts and source content are explicitly untrusted; fixed constraints and verification obligations are Skillet-owned.</p><details><summary>Show deterministic handoff JSON</summary><pre>{{.HandoffJSON}}</pre></details></section>
<section class="detail-section"><h2>Proposed artifact</h2>{{if .Proposal.PatchSHA256}}<dl class="detail-list"><div><dt>Patch SHA-256</dt><dd><code>{{.Proposal.PatchSHA256}}</code></dd></div></dl><details><summary>Show patch</summary><pre>{{.Proposal.Patch}}</pre></details>{{else}}<p class="muted">No patch attached.</p>{{end}}{{if .Proposal.ExternalReference}}<p>External review reference: <a href="{{.Proposal.ExternalReference}}" rel="noreferrer">{{.Proposal.ExternalReference}}</a></p>{{end}}</section>
<section class="detail-section"><h2>Verification history</h2>{{if .Proposal.Verification}}{{range .Proposal.Verification}}<article class="result-card"><h3>Attempt {{.Attempt}}</h3><p class="muted">Recorded by {{.ActorID}}</p>{{range .Results}}<dl class="detail-list"><div><dt>Obligation</dt><dd><code>{{.Name}}</code></dd></div><div><dt>Command</dt><dd><code>{{.Command}}</code></dd></div><div><dt>Passed</dt><dd>{{.Passed}} (exit {{.ExitCode}})</dd></div><div><dt>Summary</dt><dd>{{.Summary}}</dd></div>{{if .EvidenceRef}}<div><dt>Evidence ref</dt><dd>{{.EvidenceRef}}</dd></div>{{end}}</dl>{{end}}</article>{{end}}{{else}}<p class="muted">No verification attempt has been recorded.</p>{{end}}</section>
{{if .CanAttach}}<section class="detail-section"><h2>Attach or verify a proposed change</h2><p>Skillet records the artifact and verification evidence; it does not execute these commands. Failed results remain visible and cannot become ready-for-review.</p><form method="post" action="/ui/proposals/{{.Proposal.ID}}/artifact"><input type="hidden" name="_csrf" value="{{.CSRFToken}}"><input type="hidden" name="base_revision_id" value="{{.Proposal.Base.RevisionID}}"><label><span>Git unified diff (bounded to <code>{{.Proposal.Base.SourcePath}}</code>)</span><textarea name="patch" rows="12" spellcheck="false" placeholder="diff --git a/{{.Proposal.Base.SourcePath}}/SKILL.md b/{{.Proposal.Base.SourcePath}}/SKILL.md&#10;..."></textarea></label><label><span>External HTTPS review/PR reference (optional)</span><input type="url" name="external_reference" placeholder="https://github.com/org/repo/pull/123"></label><label><span>Verification results JSON</span><textarea name="verification_json" rows="12" required spellcheck="false">{{.VerificationExample}}</textarea></label><div class="form-actions"><button class="primary-button" type="submit">Record artifact and verification</button></div></form></section>{{end}}
{{if .CanReject}}<section class="detail-section"><h2>Close proposal</h2><form method="post" action="/ui/proposals/{{.Proposal.ID}}/reject"><input type="hidden" name="_csrf" value="{{.CSRFToken}}"><button class="secondary-button" type="submit">Reject proposal</button></form></section>{{end}}
<section class="state-card"><strong>No auto-fix or publish path</strong><p>Proposal state never changes retrieval ranking, governance, or active revisions. Source mutation remains an explicit external human-reviewed workflow.</p></section>
{{end}}</main></body></html>{{end}}`
